### ISSUE TITLE
mock数据中的图片地址挂了

### ISSUE THREAD

**Issue by gaowei1012** [imageslr/taro-library#3]
![WX20190507-212029](https://user-images.githubusercontent.com/25763661/57302542-0a6e6a80-710e-11e9-9ced-5cfdfc0b3726.png)

**Comment by imageslr** [comment]
抱歉 应该是域名到期了 我这两天看看

**Comment by imageslr** [comment]
修改了图片路径，请pull一下最新版本

**Comment by gaowei1012** [comment]
好的 感谢
