### ISSUE TITLE
按你写出现了这个问题

### ISSUE THREAD

**Issue by alvinli1008** [imageslr/taro-library#4]
这怎么发图片好，在pages/home/index
点击新书速递时他跳转页面是pages/home/pages/book-list/index?type=new
(VM17535:1 navigateTo:fail page "pages/home/pages/book-list/index?type=new" is not found)
![1111](https://user-images.githubusercontent.com/47051702/58456782-ab71a380-8157-11e9-83ae-36b9938a3631.PNG)

**Comment by alvinli1008** [comment]
这儿解决了，但不知道问题在哪，配置项吗？

**Comment by alvinli1008** [comment]
![5](https://user-images.githubusercontent.com/47051702/58464537-728dfa80-8168-11e9-93a6-0b40ff2ccbfc.PNG)

**Comment by imageslr** [comment]
我重新测试了一下，没有发现你说的这个问题。

home页面一共有三个跳转链接，都是使用`url={\`${URL.BOOK_LIST}?type=xxx\`}`的形式。如果第一个“新书速递”的跳转有问题的话，其他两个应该也会有问题吧？

`URL.BOOK_LIST`这个变量的值是`"/pages/book-list/index"`，保存在`/src/constant.js`文件中。注意这个字符串是一个**绝对路径**，一开始是`/`。

你一开始说的那个问题：跳转链接被指定为`pages/home/pages/book-list/index?type=new`，这说明变量`URL.BOOK_LIST`的值是`"pages/book-list/index"`，丢失了一开始的`/`，所以小程序框架会认为它是**相对路径**，因此把它拼接在当前页面`/pages/home`之后。

建议你`console.log(URL.BOOK_LIST)`看一下输出结果是什么。

**Comment by alvinli1008** [comment]
还正是

**Comment by imageslr** [comment]
另外这里粘贴完整代码会比较容易分析问题。可以搜一下”markdown 代码语法“

**Comment by alvinli1008** [comment]
![7](https://user-images.githubusercontent.com/47051702/58465334-090eeb80-816a-11e9-8e8b-54f6a0528b6d.PNG)
还有个问题data

**Comment by alvinli1008** [comment]
好的，谢谢你解答。如果有问题应该都是我编写过程中的问题，我会再想想
